### ISSUE TITLE
Add more options to RegistryAwareClient

### ISSUE THREAD

**Issue by chrisrohr** [kiwiproject/registry-aware-jersey-client#36]
We currently have a `targetForService` which sets up the WebTarget using the service instance's hostname, application port and home page url.  It would be nice to have at least the following option to request data from the admin port:

`public WebTarget adminTargetForService(ServiceIdentifier serviceIdentifier)`

This will setup the WebTarget with the hostname and admin port but then let the caller set the path.  We could also add:

`public WebTarget adminStatusTargetForService(ServiceIdentifier serviceIdentifier)` and `public WebTarget adminHealthCheckTargetForService(ServiceIdentifier serviceIdentifier)` that will utilize the other path objects in the ServiceInstance to set the base target.

**Comment by chrisrohr** [comment]
We _could_ add the other helpers if we wanted, but not sure that is necessary now

**Comment by sleberknight** [comment]
Maybe we need better documentation 😎

**Comment by chrisrohr** [comment]
Agreed, will change this to update the docs
