### ISSUE TITLE
Add ability to provide TlsConfigurationContext to DropwizardManagedBuilder in addition to providing TlsConfigProvider

### ISSUE THREAD

**Issue by chrisrohr** [kiwiproject/registry-aware-jersey-client#49]

**Comment by sleberknight** [comment]
We should also add an `.sslContext(SSLContext)` method in addition to the `TLSContextConfiguration`

**Comment by sleberknight** [comment]
We looked at the code, and we should _not_ add `.sslContext` method to the builder, because of the way we want to implement this internally, and because apps will pretty much always have a configuration.
