### ISSUE TITLE
Add factory method to ServiceIdentifier to create for given service name

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/registry-aware-jersey-client#93]
_Most_ of the time, in our (Dropwizard) configuration classes, we simply use

```java
@NotNull
@Value
private ServiceIdentifier myServiceId = ServiceIdentifier.builder().serviceName("my-service").build();
```

which is rather verbose. Instead, we should provide a simple factory method to permit something like this:

```java
@NotNull
@Value
private ServiceIdentifier myServiceId = ServiceIdentifier.ofName("my-service");
```

Not sure whether `ofName` should be the name, or maybe `application` to indicate it creates an instance with an `APPLICATION` connector type. `ServiceIdentifier.application("my-service")` doesn't seem as clear, though `ofName` doesn't indicate the connector type. Or maybe just `ServiceIdentifier.of("my-service")` which would allow for also having `ServiceIdentifier.of("my-service", PortType.ADMIN)` if we wanted.

**Comment by terezivy** [comment]
I'd say .of since as you said, would allow for more methods with additional items for specificity.

**Comment by chrisrohr** [comment]
Agree with @terezivy or it could be `.for` either is fine with me

**Comment by sleberknight** [comment]
I think I'll go with `of` if for no other reason than it seems to be the JDK's new "preferred" choice, e.g. Map.of, List.of, Set.of, for factories, _and_ also because `for` is a keyword (though obviously it's contextual and would not cause any actual problems).

So...

```java
ServiceIdentifier.of("my-service")
```

**Comment by sleberknight** [comment]
And I guess I may as well add an `of(String serviceName, PortType connector)` too, since we do use that on occasion for connecting to metrics, health checks, etc.
